import 'package:flutter/material.dart';
import 'package:iconsax_plus/iconsax_plus.dart';

class SettingsConstants {
  static const List<Map<String, dynamic>> sections = [
    {
      'title': 'Overview',
      'icon': Icons.dashboard_outlined,
      'description': 'Overview of all settings',
      'isHome': true,
    },
    {
      'title': 'Account Management',
      'icon': Icons.manage_accounts_outlined,
      'description': 'Manage your account details and preferences',
    },
    {
      'title': 'Content Preferences',
      'icon': Icons.article_outlined,
      'description': 'Customize your content experience',
    },
    {
      'title': 'Personalization',
      'icon': Icons.palette_outlined,
      'description': 'Customize the look and feel of your app',
    },
    {
      'title': 'App Settings',
      'icon': Icons.settings_outlined,
      'description': 'Configure general app settings',
    },
    {
      'title': 'Notifications',
      'icon': Icons.notifications_outlined,
      'description': 'Manage your notification preferences',
    },
    {
      'title': 'Privacy & Security',
      'icon': Icons.security_outlined,
      'description': 'Control your privacy and security settings',
    },
    {
      'title': 'Help & Support',
      'icon': Icons.help_outline_outlined,
      'description': 'Get help and support',
    },
    {
      'title': 'About & Legal',
      'icon': Icons.info_outline,
      'description': 'View app information and legal documents',
    },
    {
      'title': 'Critical Actions',
      'icon': Icons.warning_outlined,
      'description': 'Manage critical account actions',
    },
  ];

  static const Map<String, List<Map<String, dynamic>>> sectionContent = {
    'Account Management': [
      {
        'title': 'Google Account',
        'subtitle': 'Connect your Google account for seamless integration',
        'icon': Icons.g_mobiledata_rounded,
        'type': 'action',
        'key': 'connectGoogle',
      },
      {
        'title': 'Facebook Account',
        'subtitle': 'Link your Facebook account',
        'icon': Icons.facebook_outlined,
        'type': 'action',
        'key': 'connectFacebook',
      },
      {
        'title': 'Twitter Account',
        'subtitle': 'Connect your Twitter account',
        'icon': Icons.flutter_dash_outlined,
        'type': 'action',
        'key': 'connectTwitter',
      },
      {
        'title': 'Account Verification',
        'subtitle': 'Verify your account for additional features',
        'icon': Icons.verified_user_outlined,
        'type': 'action',
        'key': 'verifyAccount',
      },
      {
        'title': 'Account Analytics',
        'subtitle': 'View your account statistics and performance',
        'icon': Icons.analytics_outlined,
        'type': 'action',
        'key': 'viewAnalytics',
      },
      {
        'title': 'Account History',
        'subtitle': 'View your account activity history',
        'icon': Icons.history_outlined,
        'type': 'action',
        'key': 'viewHistory',
      },
    ],
    'Content Preferences': [
      {
        'title': 'Auto-play Videos',
        'subtitle': 'Automatically play videos while scrolling',
        'icon': Icons.play_circle_outline,
        'type': 'switch',
        'key': 'autoPlayVideos',
      },
      {
        'title': 'Show NSFW Content',
        'subtitle': 'Show content marked as NSFW',
        'icon': Icons.warning_amber_outlined,
        'type': 'switch',
        'key': 'showNSFWContent',
      },
      {
        'title': 'Show Reading Time',
        'subtitle': 'Display estimated reading time for articles',
        'icon': Icons.timer_outlined,
        'type': 'switch',
        'key': 'showReadingTime',
      },
      {
        'title': 'Reader Mode',
        'subtitle': 'Enable distraction-free reading experience',
        'icon': Icons.chrome_reader_mode_outlined,
        'type': 'switch',
        'key': 'readerMode',
      },
      {
        'title': 'Save Reading Progress',
        'subtitle': 'Remember where you left off in articles',
        'icon': Icons.bookmark_outline,
        'type': 'switch',
        'key': 'saveReadingProgress',
      },
      {
        'title': 'Content Language',
        'subtitle': 'Choose languages for content you see',
        'icon': Icons.translate_outlined,
        'type': 'action',
        'key': 'contentLanguage',
      },
      {
        'title': 'Adult Content Filter',
        'subtitle': 'Control visibility of mature content',
        'icon': Icons.block_outlined,
        'type': 'switch',
        'key': 'adultContentFilter',
      },
    ],
    'Personalization': [
      {
        'title': 'Theme Browser',
        'subtitle': 'Browse and customize themes',
        'icon': Icons.style_outlined,
        'type': 'action',
        'key': 'themeBrowser',
      },
      {
        'title': 'Theme',
        'subtitle': 'Choose your preferred theme',
        'icon': Icons.dark_mode_outlined,
        'type': 'switch',
        'key': 'isDarkMode',
      },
      {
        'title': 'Background Effects',
        'subtitle': 'Choose your preferred background effect',
        'icon': Icons.blur_on_outlined,
        'type': 'custom',
        'key': 'backgroundEffect',
      },
      {
        'title': 'Neon Effects',
        'subtitle': 'Enable neon glow effects',
        'icon': Icons.light_mode_outlined,
        'type': 'switch',
        'key': 'neonEffectEnabled',
      },
      {
        'title': 'Neon Effect Speed',
        'subtitle': 'Adjust the speed of neon effects',
        'icon': Icons.speed_outlined,
        'type': 'slider',
        'key': 'neonEffectSpeed',
        'min': 0.25,
        'max': 5.0,
      },
      {
        'title': 'Neon Effect Intensity',
        'subtitle': 'Adjust the intensity of neon effects',
        'icon': Icons.brightness_6_outlined,
        'type': 'slider',
        'key': 'neonEffectIntensity',
        'min': 0.0,
        'max': 1.0,
      },
      {
        'title': 'Neon Effect Width',
        'subtitle': 'Adjust the width of neon effects',
        'icon': Icons.line_weight_outlined,
        'type': 'slider',
        'key': 'neonEffectWidth',
        'min': 1.0,
        'max': 10.0,
      },
      {
        'title': 'Neon Effect Pulsing',
        'subtitle': 'Enable pulsing animation for neon effects',
        'icon': Icons.animation_outlined,
        'type': 'switch',
        'key': 'neonEffectPulsing',
      },
      {
        'title': 'Text Size',
        'subtitle': 'Adjust the size of text throughout the app',
        'icon': Icons.text_fields_outlined,
        'type': 'slider',
        'key': 'textSize',
        'min': 0.8,
        'max': 1.4,
      },
      {
        'title': 'High Contrast',
        'subtitle': 'Increase contrast for better visibility',
        'icon': Icons.contrast_outlined,
        'type': 'switch',
        'key': 'highContrast',
      },
    ],
    'App Settings': [
      {
        'title': 'Data Saver',
        'subtitle': 'Reduce data usage',
        'icon': Icons.data_saver_off_outlined,
        'type': 'switch',
        'key': 'dataSaver',
      },
      {
        'title': 'Background Refresh',
        'subtitle': 'Keep content up to date',
        'icon': Icons.refresh_outlined,
        'type': 'switch',
        'key': 'backgroundRefresh',
      },
      {
        'title': 'Storage',
        'subtitle': 'Manage app storage',
        'icon': Icons.storage_outlined,
        'type': 'action',
        'key': 'storage',
      },
      {
        'title': 'Clear Cache',
        'subtitle': 'Free up space',
        'icon': Icons.cleaning_services_outlined,
        'type': 'action',
        'key': 'clearCache',
      },
      {
        'title': 'Screen Reader',
        'subtitle': 'Enable screen reader support',
        'icon': Icons.accessibility_new_outlined,
        'type': 'switch',
        'key': 'screenReader',
      },
      {
        'title': 'Reduce Motion',
        'subtitle': 'Minimize animations',
        'icon': Icons.animation_outlined,
        'type': 'switch',
        'key': 'reduceMotion',
      },
      {
        'title': 'Keyboard Shortcuts',
        'subtitle': 'View and customize shortcuts',
        'icon': Icons.keyboard_outlined,
        'type': 'action',
        'key': 'keyboardShortcuts',
      },
      {
        'title': 'Developer Mode',
        'subtitle': 'Enable developer options',
        'icon': Icons.developer_mode_outlined,
        'type': 'switch',
        'key': 'developerMode',
      },
      {
        'title': 'Export Settings',
        'subtitle': 'Export your settings',
        'icon': Icons.upload_outlined,
        'type': 'action',
        'key': 'exportSettings',
      },
      {
        'title': 'Reset Settings',
        'subtitle': 'Reset to default settings',
        'icon': Icons.restore_outlined,
        'type': 'action',
        'key': 'resetSettings',
      },
    ],
    'Notifications': [
      {
        'title': 'Push Notifications',
        'subtitle': 'Enable push notifications',
        'icon': Icons.notifications_active_outlined,
        'type': 'switch',
        'key': 'pushNotifications',
      },
      {
        'title': 'Email Notifications',
        'subtitle': 'Enable email notifications',
        'icon': Icons.email_outlined,
        'type': 'switch',
        'key': 'emailNotifications',
      },
      {
        'title': 'Browser Notifications',
        'subtitle': 'Enable browser notifications',
        'icon': Icons.web_outlined,
        'type': 'switch',
        'key': 'browserNotifications',
      },
      {
        'title': 'Mention Notifications',
        'subtitle': 'Get notified when someone mentions you',
        'icon': Icons.alternate_email_outlined,
        'type': 'switch',
        'key': 'mentionNotifications',
      },
      {
        'title': 'Reaction Notifications',
        'subtitle': 'Get notified when someone reacts to your content',
        'icon': Icons.thumb_up_outlined,
        'type': 'switch',
        'key': 'reactionNotifications',
      },
      {
        'title': 'Follower Notifications',
        'subtitle': 'Get notified when someone follows you',
        'icon': Icons.person_add_outlined,
        'type': 'switch',
        'key': 'followerNotifications',
      },
      {
        'title': 'Message Notifications',
        'subtitle': 'Get notified when you receive messages',
        'icon': Icons.message_outlined,
        'type': 'switch',
        'key': 'messageNotifications',
      },
      {
        'title': 'Community Notifications',
        'subtitle': 'Get notified about community updates',
        'icon': Icons.group_outlined,
        'type': 'switch',
        'key': 'communityNotifications',
      },
      {
        'title': 'Update Notifications',
        'subtitle': 'Get notified about app updates',
        'icon': Icons.system_update_outlined,
        'type': 'switch',
        'key': 'updateNotifications',
      },
      {
        'title': 'Newsletter Notifications',
        'subtitle': 'Get notified about newsletters',
        'icon': Icons.newspaper_outlined,
        'type': 'switch',
        'key': 'newsletterNotifications',
      },
      {
        'title': 'Offer Notifications',
        'subtitle': 'Get notified about special offers',
        'icon': Icons.local_offer_outlined,
        'type': 'switch',
        'key': 'offerNotifications',
      },
      {
        'title': 'New Post Notifications',
        'subtitle': 'Get notified about new posts',
        'icon': Icons.post_add_outlined,
        'type': 'switch',
        'key': 'newPostNotifications',
      },
      {
        'title': 'Comment Notifications',
        'subtitle': 'Get notified about comments',
        'icon': Icons.comment_outlined,
        'type': 'switch',
        'key': 'commentNotifications',
      },
    ],
    'Privacy & Security': [
      {
        'title': 'Two-Factor Authentication',
        'subtitle': 'Add an extra layer of security',
        'icon': Icons.security_outlined,
        'type': 'switch',
        'key': 'twoFactorEnabled',
      },
      {
        'title': 'Private Profile',
        'subtitle': 'Make your profile private',
        'icon': Icons.visibility_off_outlined,
        'type': 'switch',
        'key': 'privateProfile',
      },
      {
        'title': 'Private Posts',
        'subtitle': 'Make your posts private by default',
        'icon': Icons.lock_outline,
        'type': 'switch',
        'key': 'privatePostsEnabled',
      },
      {
        'title': 'Activity Status',
        'subtitle': 'Show when you are active',
        'icon': Icons.access_time_outlined,
        'type': 'switch',
        'key': 'activityStatusEnabled',
      },
      {
        'title': 'Read Receipts',
        'subtitle': 'Show when you have read messages',
        'icon': Icons.done_all_outlined,
        'type': 'switch',
        'key': 'readReceiptsEnabled',
      },
      {
        'title': 'Data Collection',
        'subtitle': 'Allow data collection for better experience',
        'icon': Icons.data_usage_outlined,
        'type': 'switch',
        'key': 'dataCollectionEnabled',
      },
      {
        'title': 'Third-Party Access',
        'subtitle': 'Manage third-party app access',
        'icon': Icons.apps_outlined,
        'type': 'switch',
        'key': 'thirdPartyAccessEnabled',
      },
      {
        'title': 'Personalized Ads',
        'subtitle': 'Allow personalized advertisements',
        'icon': Icons.ads_click_outlined,
        'type': 'switch',
        'key': 'personalizedAdsEnabled',
      },
      {
        'title': 'Login Alerts',
        'subtitle': 'Get notified of new login attempts',
        'icon': Icons.login_outlined,
        'type': 'switch',
        'key': 'loginAlertsEnabled',
      },
      {
        'title': 'Suspicious Activity Alerts',
        'subtitle': 'Get notified of suspicious activity',
        'icon': Icons.gpp_maybe_outlined,
        'type': 'switch',
        'key': 'suspiciousActivityAlertsEnabled',
      },
    ],
    'Help & Support': [
      {
        'title': 'FAQ',
        'subtitle': 'Frequently asked questions',
        'icon': Icons.help_outline,
        'type': 'action',
        'key': 'faq',
      },
      {
        'title': 'Contact Support',
        'subtitle': 'Get in touch with our support team',
        'icon': Icons.support_agent_outlined,
        'type': 'action',
        'key': 'contactSupport',
      },
      {
        'title': 'Live Chat',
        'subtitle': 'Chat with our support team',
        'icon': Icons.chat_outlined,
        'type': 'action',
        'key': 'liveChat',
      },
      {
        'title': 'Support Tickets',
        'subtitle': 'View your support tickets',
        'icon': Icons.confirmation_number_outlined,
        'type': 'action',
        'key': 'supportTickets',
      },
      {
        'title': 'Report a Bug',
        'subtitle': 'Help us improve by reporting bugs',
        'icon': Icons.bug_report_outlined,
        'type': 'action',
        'key': 'reportBug',
      },
      {
        'title': 'Feature Request',
        'subtitle': 'Suggest new features',
        'icon': Icons.lightbulb_outline,
        'type': 'action',
        'key': 'featureRequest',
      },
      {
        'title': 'Rate App',
        'subtitle': 'Rate your experience',
        'icon': Icons.star_outline,
        'type': 'action',
        'key': 'rateApp',
      },
    ],
    'About & Legal': [
      {
        'title': 'About Blogify',
        'subtitle': 'Learn more about Blogify',
        'icon': Icons.info_outline,
        'type': 'action',
        'key': 'aboutBlogify',
      },
      {
        'title': "What's New",
        'subtitle': 'See latest updates and changes',
        'icon': Icons.new_releases_outlined,
        'type': 'action',
        'key': 'whatsNew',
      },
      {
        'title': 'Credits',
        'subtitle': 'View credits and acknowledgments',
        'icon': Icons.people_outline,
        'type': 'action',
        'key': 'credits',
      },
      {
        'title': 'Terms of Service',
        'subtitle': 'Read our terms of service',
        'icon': Icons.description_outlined,
        'type': 'action',
        'key': 'termsOfService',
      },
      {
        'title': 'Privacy Policy',
        'subtitle': 'Read our privacy policy',
        'icon': Icons.policy_outlined,
        'type': 'action',
        'key': 'privacyPolicy',
      },
      {
        'title': 'Cookie Policy',
        'subtitle': 'Read our cookie policy',
        'icon': Icons.cookie_outlined,
        'type': 'action',
        'key': 'cookiePolicy',
      },
      {
        'title': 'Open Source Licenses',
        'subtitle': 'View open source licenses',
        'icon': Icons.source_outlined,
        'type': 'action',
        'key': 'openSourceLicenses',
      },
      {
        'title': 'Software Licenses',
        'subtitle': 'View software licenses',
        'icon': Icons.verified_outlined,
        'type': 'action',
        'key': 'softwareLicenses',
      },
      {
        'title': 'Content Licenses',
        'subtitle': 'View content licenses',
        'icon': Icons.copyright_outlined,
        'type': 'action',
        'key': 'contentLicenses',
      },
    ],
    'Critical Actions': [
      {
        'title': 'Delete Account',
        'subtitle': 'Permanently delete your account',
        'icon': Icons.delete_forever_outlined,
        'type': 'action',
        'key': 'deleteAccount',
      },
      {
        'title': 'Export Data',
        'subtitle': 'Export all your data',
        'icon': Icons.download_outlined,
        'type': 'action',
        'key': 'exportData',
      },
    ],
  };
}
